/**
 * Statically bundled list of known disposable / temporary email domains.
 * Sources: disposable-email-domains (MIT), mailcheck.ai, various community lists.
 * O(1) Set lookup — no I/O, no network.
 */
const DISPOSABLE_DOMAINS = new Set([
  // ── Most common ────────────────────────────────────────────────────────────
  "yopmail.com", "yopmail.fr", "cool.fr.nf", "jetable.fr.cool", "nospam.ze.tc",
  "nomail.xl.cx", "mega.zik.dj", "speed.1s.fr", "courriel.fr.nf", "moncourrier.fr.nf",
  "monemail.fr.nf", "monmail.fr.nf",
  "mailinator.com", "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
  "guerrillamail.de", "guerrillamail.biz", "guerrillamail.info",
  "sharklasers.com", "guerrillamailblock.com", "grr.la", "guerrillamail.info",
  "spam4.me", "trashmail.com", "trashmail.at", "trashmail.io", "trashmail.me",
  "trashmail.net", "trashmail.org", "trashmail.xyz",
  "tempmail.com", "temp-mail.org", "temp-mail.io", "tempmail.net",
  "10minutemail.com", "10minutemail.net", "10minutemail.org",
  "throwam.com", "throwam.net",
  "mailnull.com", "maildrop.cc",
  "dispostable.com", "disposeamail.com",
  "fakeinbox.com", "fakeinbox.net",
  "mailnesia.com", "mailnesia.net",
  "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
  "spamgourmet.com", "spaml.com",
  "getnada.com", "getairmail.com",
  "discard.email", "discardmail.com", "discardmail.de",
  "burnermail.io",
  "tempr.email", "tempm.com",
  "filzmail.com", "filzmail.de",
  "throwam.com",
  "nwldx.com", "rcpt.at",
  "spamhereplease.com", "spamhereplease.net",
  "nospamfor.us", "nospam4.us",
  "spamfree24.org", "spamfree.eu",
  "throwam.net",
  "spamgob.com",
  "mailexpire.com",
  "mailbucket.org",
  "maileater.com",
  "mailscrap.com",
  "spamherelots.com",
  "spamherewhat.com",
  "dontreg.com",
  "dontsendmespam.de",
  "emailsensei.com",
  "emailtemporanea.com",
  "emailtemporanea.net",
  "emailtemporario.com.br",
  "fakemailgenerator.com",
  "fakemail.fr",
  "filzmail.com",
  "gowikibooks.com",
  "gowikicampus.com",
  "gowikicars.com",
  "gowikifilms.com",
  "gowikigames.com",
  "gowikimusic.com",
  "gowikinetwork.com",
  "gowikitravel.com",
  "gowikitv.com",
  "haltospam.com",
  "jetable.com", "jetable.fr", "jetable.net", "jetable.org",
  "kasmail.com",
  "klassmaster.com",
  "klassmaster.net",
  "lol.ovpn.to",
  "maileater.com",
  "mailexpire.com",
  "mailimate.com",
  "mailinator2.com",
  "mailme.lv",
  "mailnew.com",
  "mailnull.com",
  "mailtome.de",
  "mailzilla.com", "mailzilla.org",
  "mega.zik.dj",
  "meltmail.com",
  "mierdamail.com",
  "moburl.com",
  "nospamthanks.info",
  "notmailinator.com",
  "nowhere.org",
  "nomail.pw",
  "objectmail.com",
  "obobbo.com",
  "odaymail.com",
  "oneoffmail.com",
  "onewaymail.com",
  "ordinaryamerican.net",
  "owlpic.com",
  "pancakemail.com",
  "pookmail.com",
  "privy-mail.com", "privy-mail.de",
  "proxymail.eu",
  "putthisinyourspamdatabase.com",
  "quickinbox.com",
  "rcpt.at",
  "rklips.com",
  "rmqkr.net",
  "rtrtr.com",
  "s0ny.net",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "selfdestructingmail.com",
  "sendspamhere.com",
  "sharklasers.com",
  "sharedmailbox.org",
  "shiftmail.com",
  "shitmail.me", "shitmail.org",
  "shitware.nl",
  "shortmail.net",
  "sibmail.com",
  "smellfear.com",
  "snkmail.com",
  "sofimail.com",
  "sogetthis.com",
  "spammotel.com",
  "spamoff.de",
  "spamsalad.in",
  "spamslicer.com",
  "spamspot.com",
  "spamstack.net",
  "spamthisplease.com",
  "spamtrail.com",
  "stop-my-spam.com", "stop-my-spam.pp.ua",
  "supergreatmail.com",
  "suremail.info",
  "sweetxxx.de",
  "tafmail.com",
  "tagyourself.com",
  "talkinator.com",
  "teleworm.com", "teleworm.us",
  "tempalias.com",
  "tempe-mail.com",
  "tempemail.biz", "tempemail.com", "tempemail.net",
  "tempinbox.co.uk", "tempinbox.com",
  "templmail.com",
  "temporaryemail.net", "temporaryemail.us",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymail.org",
  "tempthe.net",
  "thanksnospam.info",
  "thisisnotmyrealemail.com",
  "throwam.com",
  "throwmail.me",
  "tilien.com",
  "tittbit.in",
  "tmail.com",
  "tmail.io",
  "tmailinator.com",
  "toiea.com",
  "tradermail.info",
  "trash-amil.com",
  "trash-mail.at", "trash-mail.com", "trash-mail.de", "trash-mail.ga", "trash-mail.io",
  "trash2009.com",
  "trashdevil.com", "trashdevil.de",
  "trashemail.de",
  "trashimail.de",
  "trashmail.at", "trashmail.com", "trashmail.de", "trashmail.io", "trashmail.me",
  "trashmail.net", "trashmail.org", "trashmail.xyz",
  "trashmailer.com",
  "trashspam.com",
  "trasz.com",
  "trbvm.com",
  "trillianpro.com",
  "tryalert.com",
  "ttirv.com", "ttirv.net", "ttirv.org",
  "turual.com",
  "twinmail.de",
  "twoweirdtricks.com",
  "tyldd.com",
  "uggsrock.com",
  "umail.net",
  "uroid.com",
  "username.e4ward.com",
  "valemail.net",
  "venompen.com",
  "viditag.com",
  "vomoto.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",
  "walala.org",
  "walkmail.net",
  "webemail.me",
  "webm4il.info",
  "weg-werf-email.de",
  "wegwerf-emails.de",
  "wetrainbayarea.com", "wetrainbayarea.org",
  "wilemail.com",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "wphxqg.com",
  "writeme.us",
  "wronghead.com",
  "wuzupmail.net",
  "www.e4ward.com",
  "xagloo.co", "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xmaily.com",
  "xoxy.net",
  "xyzfree.net",
  "yapped.net",
  "yeah.net",
  "yep.it",
  "yogamaven.com",
  "yopmail.com", "yopmail.fr",
  "ypmail.webarnak.fr.eu.org",
  "yuurok.com",
  "z1p.biz",
  "za.com",
  "zehnminutenmail.de",
  "zetmail.com",
  "zippymail.info",
  "zoaxe.com",
  "zoemail.net", "zoemail.org",
  "zomg.info",
  "inoutmail.de", "inoutmail.eu", "inoutmail.info", "inoutmail.net",
  "mailnull.com",
  "spam.la",
  "spam.su",
  "spamavert.com",
  "binkmail.com",
  "bob.email",
  "boxtemp.com.br",
  "chacuo.net",
  "cincinow.net",
  "clixser.com",
  "crapmail.org",
  "crazymailing.com",
  "cubiclink.com",
  "curryworld.de",
  "cust.in",
  "dacoolest.com",
  "dandikmail.com",
  "dayrep.com",
  "deadaddress.com",
  "deadletter.ga",
  "deagot.com",
  "dealja.com",
  "despam.it",
  "despammed.com",
  "devnullmail.com",
  "dfgh.net",
  "digitalsanctuary.com",
  "dingbone.com",
  "disposableaddress.com",
  "disposableemailaddresses.com",
  "disposableemailaddresses.emailmiser.com",
  "disposableinbox.com",
  "dispose.it",
  "dispostable.com",
  "dodgeit.com",
  "dodgit.com", "dodgit.org",
  "donemail.ru",
  "dontmail.net",
  "dontreg.com",
  "dontsendmespam.de",
  "drdrb.com", "drdrb.net",
  "dump-email.info",
  "dumpandfuck.com",
  "dumpmail.de",
  "dumpyemail.com",
  "e4ward.com",
  "easytrashmail.com",
  "einrot.com", "einrot.de",
  "email60.com",
  "emailias.com",
  "emailigo.com",
  "emailinfive.com",
  "emailisvalid.com",
  "emailmiser.com",
  "emailproxsy.com",
  "emailsensei.com",
  "emailtemporanea.com", "emailtemporanea.net",
  "emailtemporario.com.br",
  "emailthe.net",
  "emailtmp.com",
  "emailwarden.com",
  "emailx.at.hm",
  "emailxfer.com",
  "emkei.ga",
  "emkei.gq",
  "emz.net",
  "enterto.com",
  "ephemail.net",
  "etranquil.com", "etranquil.net", "etranquil.org",
  "evopo.com",
  "explodemail.com",
  "express.net.ua",
  "extremail.ru",
  "eyepaste.com",
  "fake-box.com",
  "fake-email.pp.ua",
  "fakeinbox.com",
  "fakeinformation.com",
  "fastacura.com",
  "fastem.com",
  "fastemail.us",
  "fastemailer.com",
  "fastest.cc",
  "fastimap.com",
  "fastmazda.com",
  "fastmitsubishi.com",
  "fastnissan.com",
  "fastsubaru.com",
  "fastsuzuki.com",
  "fasttoyota.com",
  "fastyamaha.com",
  "filzmail.com", "filzmail.de",
  "fizmail.com",
  "fleckens.hu",
  "flurred.com",
  "flyspam.com",
  "footard.com",
  "forgetmail.com",
  "forward.cat",
  "fr33mail.info",
  "frapmail.com",
  "friendlymail.co.uk",
  "front14.org",
  "fuckingduh.com",
  "fuckmail.me",
  "fudgerub.com",
  "fux0ringduh.com",
  "garliclife.com",
  "get1mail.com",
  "getairmail.com",
  "getmails.eu",
  "getonemail.com", "getonemail.net",
  "gishpuppy.com",
  "gmail.com.sg",
  "go2usa.info",
  "go4.it",
  "grr.la",
  "gsrv.co.uk",
  "guerrillamail.biz", "guerrillamail.com", "guerrillamail.de", "guerrillamail.info",
  "guerrillamail.net", "guerrillamail.org",
  "guerrillamailblock.com",
  "gustr.com",
  "harakirimail.com",
  "hat-geld.de",
  "hatespam.org",
  "herp.in",
  "hidemail.de",
  "hidzz.com",
  "hmamail.com",
  "hochsitze.com",
  "hotpop.com",
  "hulapla.de",
  "humaility.com",
  "hvastudiesucces.nl",
  "ieatspam.eu", "ieatspam.info",
  "ieh-mail.de",
  "ignoremail.com",
  "ihateyoualot.info",
  "iheartspam.org",
  "ikbenspamvrij.nl",
  "imails.info",
  "inbax.tk",
  "inbox.si",
  "inboxalias.com",
  "incognitomail.com", "incognitomail.net", "incognitomail.org",
  "inemail.com",
  "infectedmouse.org",
  "infocom.zp.ua",
  "inmailbox.com",
  "instant-mail.de",
  "ipoo.org",
  "irc.so",
  "iwi.net",
  "jetable.com", "jetable.fr", "jetable.net", "jetable.org",
  "jnxjn.com",
  "jobbikmailer.com",
  "jobs-to-be-done.net",
  "junk.to",
  "junk1.tk",
  "junkmail.com", "junkmail.ga", "junkmail.gq",
  "jupimail.com",
  "kasmail.com",
  "kaspop.com",
  "keep.plus",
  "killmail.com", "killmail.net",
  "klzlk.com",
  "koszmail.pl",
  "kulmus.com",
  "kurzepost.de",
  "laste.ml",
  "lawlita.com",
  "lazyinbox.com",
  "letthemeatspam.com",
  "lol.ovpn.to",
  "lookugly.com",
  "lortemail.dk",
  "lovemeleaveme.com",
  "lr78.com",
  "lroid.com",
  "lukop.dk",
  "m4ilweb.info",
  "maboard.com",
  "mail-filter.com",
  "mail-temporaire.com", "mail-temporaire.fr",
  "mail.mezimages.net",
  "mail1a.de",
  "mail21.cc",
  "mail2rss.org",
  "mail333.com",
  "mailbidon.com",
  "mailbiz.biz",
  "mailblocks.com",
  "mailbucket.org",
  "mailc.net",
  "mailcan.com",
  "mailcat.biz",
  "mailcatch.com",
  "mailde.de", "mailde.info",
  "maildu.de",
  "maileater.com",
  "mailed.ro",
  "maileme101.com",
  "mailexpire.com",
  "mailfa.tk",
  "mailforspam.com",
  "mailfreeonline.com",
  "mailguard.me",
  "mailhazard.com", "mailhazard.us",
  "mailimate.com",
  "mailim.co.cc",
  "mailinater.com",
  "mailinator.com", "mailinator.net", "mailinator.org",
  "mailinator2.com",
  "mailismagic.com",
  "mailme.lv",
  "mailme24.com",
  "mailmetrash.com",
  "mailmoat.com",
  "mailnew.com",
  "mailnull.com",
  "mailpick.biz",
  "mailproxsy.com",
  "mailquack.com",
  "mailrock.biz",
  "mailsac.com",
  "mailscrap.com",
  "mailseal.de",
  "mailshell.com",
  "mailsiphon.com",
  "mailslapping.com",
  "mailslite.com",
  "mailsroom.com",
  "mailsucker.net",
  "mailt.ru",
  "mailtemporal.com",
  "mailtemporaire.fr",
  "mailthis.in",
  "mailtra.in",
  "mailtrim.com",
  "mailtv.net", "mailtv.tv",
  "mailzilla.com", "mailzilla.org",
  "makemetheking.com",
  "manybrain.com",
  "mbx.cc",
  "mega.zik.dj",
  "meltmail.com",
  "messagebeamer.de",
  "mezimages.net",
  "mierdamail.com",
  "mintemail.com",
  "moburl.com",
  "mohmal.com",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "mopick.com",
  "mr24.cc",
  "mrsrinivasan.com",
  "mt2009.com",
  "mt2014.com",
  "mucincanon.com",
  "mucki.at",
  "munouburo.com",
  "myfastmail.com",
  "mymail-in.net",
  "mypacks.net",
  "mypartyclip.de",
  "myphantomemail.com",
  "myspaceinc.com", "myspaceinc.net", "myspaceinc.org",
  "myspamless.com",
  "mytemp.email",
  "mytempemail.com",
  "mytempmail.com",
  "mytrashmail.com",
  "nabuma.com",
  "neomailbox.com",
  "nepwk.com",
  "nervmich.net",
  "nervtmich.net",
  "netmails.com", "netmails.net",
  "newmail.top",
  "nfast.net",
  "nice-4u.com",
  "nincsmail.hu",
  "nmail.cf",
  "nnot.net",
  "no-spam.ws",
  "noblepioneer.com",
  "nobulk.com",
  "nomail.pw",
  "nomail.xl.cx",
  "nomail2me.com",
  "nospam.ze.tc",
  "nospamfor.us",
  "nospamthanks.info",
  "notmailinator.com",
  "nowhere.org",
  "nowmymail.com",
  "nwldx.com",
  "objectmail.com",
  "obobbo.com",
  "odaymail.com",
  "oe.cd",
  "omail.pro",
  "one-time.email",
  "oneoffmail.com",
  "onewaymail.com",
  "online.ms",
  "onqin.com",
  "oplettelse.dk",
  "optedin.com",
  "ordinaryamerican.net",
  "owlpic.com",
  "pancakemail.com",
  "paplease.com",
  "pcusers.otherinbox.com",
  "pepbot.com",
  "pjjkp.com",
  "plexolan.de",
  "pm.me", // ProtonMail disposable alias
  "pokemail.net",
  "pookmail.com",
  "pop3.xyz",
  "postacı.pl",
  "posta.store",
  "powered.name",
  "privy-mail.com", "privy-mail.de",
  "proxymail.eu",
  "prtnx.com",
  "punkass.com",
  "putthisinyourspamdatabase.com",
  "quickinbox.com",
  "quickmail.nl",
  "rcpt.at",
  "recode.me",
  "regbypass.comsafe-mail.net",
  "reversiblemails.com",
  "rklips.com",
  "rmqkr.net",
  "robot-mail.com",
  "rtrtr.com",
  "s0ny.net",
  "safe-mail.ga",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "selfdestructingmail.com",
  "sendspamhere.com",
  "sharedmailbox.org",
  "shiftmail.com",
  "shortmail.net",
  "sibmail.com",
  "smellfear.com",
  "snkmail.com",
  "sofimail.com",
  "sogetthis.com",
  "spam.la",
  "spam.su",
  "spamavert.com",
  "spamfree24.org",
  "spamgob.com",
  "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
  "spamhereplease.com",
  "spamherelots.com",
  "spamherewhat.com",
  "spamhole.com",
  "spaml.com",
  "spammotel.com",
  "spamnot.com",
  "spamoff.de",
  "spamsalad.in",
  "spamslicer.com",
  "spamspot.com",
  "spamstack.net",
  "spamthisplease.com",
  "spamtrail.com",
  "speed.1s.fr",
  "sry.li",
  "stop-my-spam.com",
  "supergreatmail.com",
  "suremail.info",
  "sweetxxx.de",
  "tafmail.com",
  "tagyourself.com",
  "talkinator.com",
  "teleworm.com", "teleworm.us",
  "tempalias.com",
  "tempe-mail.com",
  "tempemail.biz", "tempemail.com", "tempemail.net",
  "tempinbox.co.uk", "tempinbox.com",
  "tempmail.com", "tempmail.net", "tempmail.org",
  "temporaryemail.net", "temporaryemail.us",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymail.org",
  "temp-mail.org", "temp-mail.io",
  "thanksnospam.info",
  "thisisnotmyrealemail.com",
  "throwam.com",
  "throwmail.me",
  "tilien.com",
  "tmail.com", "tmail.io",
  "tmailinator.com",
  "toiea.com",
  "tradermail.info",
  "trash-amil.com",
  "trash-mail.at", "trash-mail.com", "trash-mail.de", "trash-mail.ga", "trash-mail.io",
  "trashdevil.com", "trashdevil.de",
  "trashemail.de",
  "trashimail.de",
  "trashmail.at", "trashmail.com", "trashmail.de", "trashmail.io", "trashmail.me",
  "trashmail.net", "trashmail.org", "trashmail.xyz",
  "trashmailer.com",
  "trashspam.com",
  "trasz.com",
  "trbvm.com",
  "tryalert.com",
  "turual.com",
  "twinmail.de",
  "tyldd.com",
  "uggsrock.com",
  "valemail.net",
  "venompen.com",
  "viditag.com",
  "vomoto.com",
  "vsimcard.com",
  "vubby.com",
  "walala.org",
  "walkmail.net",
  "webemail.me",
  "weg-werf-email.de",
  "wegwerf-emails.de",
  "wilemail.com",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "wphxqg.com",
  "writeme.us",
  "wronghead.com",
  "wuzupmail.net",
  "xagloo.co", "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xmaily.com",
  "xoxy.net",
  "xyzfree.net",
  "yapped.net",
  "yogamaven.com",
  "yuurok.com",
  "z1p.biz",
  "zehnminutenmail.de",
  "zetmail.com",
  "zippymail.info",
  "zoaxe.com",
  "zoemail.net", "zoemail.org",
  "zomg.info",
]);

/**
 * Returns true if the email's domain is a known disposable/temporary provider.
 * O(1) Set lookup — no I/O, no external calls.
 */
export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf("@");
  if (at < 0) return false;
  const domain = email.slice(at + 1).toLowerCase().trim();
  return DISPOSABLE_DOMAINS.has(domain);
}
