import { describe, it, expect } from "vitest";
import { buildAutoFormPage } from "@/lib/admin/autoFormView";

describe("buildAutoFormPage", () => {
  const form = { id: "11111111-2222-3333-4444-555555555555", slug: "inscription", name: "Inscription" };

  it("produces a page with a single submissions_table widget bound to the form", () => {
    const page = buildAutoFormPage(form);
    expect(page.formInstanceId).toBe(form.id);
    expect(page.autoGeneratedFor).toBe(form.id);
    expect(page.widgets).toHaveLength(1);
    expect(page.widgets[0].type).toBe("submissions_table");
  });

  it("derives a deterministic id from the form id (idempotent across calls)", () => {
    const a = buildAutoFormPage(form);
    const b = buildAutoFormPage(form);
    expect(a.id).toBe(b.id);
  });

  it("turns the form slug into a URL-safe page slug", () => {
    const page = buildAutoFormPage({ id: "x", slug: "inscription", name: "x" });
    expect(page.slug).toMatch(/^form-[a-z0-9_-]+$/);
  });

  it("handles a root-style form slug ('/') without leaving leading underscores", () => {
    // Root home pages use '/' as their slug — the helper must produce a usable
    // page slug instead of `form-_` which would be ugly and route oddly.
    const page = buildAutoFormPage({ id: "x", slug: "/", name: "Home" });
    expect(page.slug.startsWith("_")).toBe(false);
  });

  it("disables the completion funnel by default (often not meaningful for a generic table view)", () => {
    expect(buildAutoFormPage(form).showCompletionFunnel).toBe(false);
  });

  it("uses the form name as the page title", () => {
    expect(buildAutoFormPage(form).title).toBe("Inscription");
  });
});
