/**
 * Auto-generated dashboard pages for each form instance.
 *
 * When `admin.features.autoCreateDashboardPageOnFormCreate` is on, every form
 * created via the API, the YAML boot upsert, or the backup/restore endpoint
 * gets a companion dashboard page with a `submissions_table` widget filtered
 * to that form.
 *
 * The page is tied to the form's id through two paths:
 *   - `formInstanceId` — the runtime filter used by the dashboard
 *   - `autoGeneratedFor` — the marker the platform reads to know "this page
 *     belongs to this form, delete it together with the form"
 *
 * Manually created pages MUST NOT set `autoGeneratedFor`. Doing so would
 * cause them to be removed at form deletion.
 *
 * The functions in this file mutate `adminConfig.pages` via the central
 * config service; they're a no-op in `file` mode (where the static
 * `form.config.ts` is the source of truth and `saveFormConfig` skips writes).
 */
import { getFormConfig, saveFormConfig, isConfigEditable } from "@/lib/config";
import { listFormInstances } from "@/lib/db/formInstanceLoader";
import { logAdminEvent } from "@/lib/db/adminAudit";
import type { AdminPage, WidgetDef } from "@/types/config";

export interface FormRefForAutoPage {
  id:   string;
  slug: string;
  name: string;
}

/**
 * Slug used in the page URL. The page id is also derived from the form's
 * slug so it's stable across reloads (and round-trips through the YAML
 * restore endpoint which keys pages by id).
 */
function pageSlugForForm(formSlug: string): string {
  return `form-${formSlug.replace(/\//g, "_").replace(/^_+/, "")}`;
}

function pageIdForForm(formId: string): string {
  // Prefix kept short — page ids live inside JSON arrays so keep them readable.
  return `auto-form-${formId}`;
}

/**
 * Pure builder — no DB I/O. Useful in tests and for the YAML import path
 * that wants a candidate page object before deciding whether to persist it.
 */
export function buildAutoFormPage(form: FormRefForAutoPage): AdminPage {
  const widget: WidgetDef = {
    type:  "submissions_table",
    id:    `${pageIdForForm(form.id)}-table`,
    title: `${form.name} — soumissions`,
  };
  return {
    id:               pageIdForForm(form.id),
    title:            form.name,
    slug:             pageSlugForForm(form.slug),
    icon:             "Table",
    widgets:          [widget],
    formInstanceId:   form.id,
    autoGeneratedFor: form.id,
    showCompletionFunnel: false,
  };
}

/**
 * Append an auto-page for `form` if (a) the toggle is on, (b) no page is
 * already bound to that form id, and (c) the config is editable (DB mode).
 *
 * Idempotent: re-running on a form that already has a page (auto or manual)
 * is a no-op. Returns `true` iff a page was actually appended.
 */
export async function ensureAutoViewForForm(form: FormRefForAutoPage): Promise<boolean> {
  if (!isConfigEditable()) return false;
  const config = await getFormConfig();
  if (!config.admin.features?.autoCreateDashboardPageOnFormCreate) return false;

  const pages = config.admin.pages ?? [];
  // A pre-existing page matching this form by id, slug, or formInstanceId
  // wins — we never duplicate or overwrite operator work.
  const alreadyExists = pages.some(
    (p) => p.formInstanceId === form.id || p.id === pageIdForForm(form.id),
  );
  if (alreadyExists) return false;

  const newPage = buildAutoFormPage(form);
  await saveFormConfig({
    ...config,
    admin: { ...config.admin, pages: [...pages, newPage] },
  });
  return true;
}

/**
 * Remove every page tagged `autoGeneratedFor === formId`. Called from the
 * DELETE form endpoint. No-op if nothing matches or config isn't editable.
 *
 * Returns the count of pages removed (for logging / admin audit details).
 */
export async function removeAutoViewForForm(formId: string): Promise<number> {
  if (!isConfigEditable()) return 0;
  const config = await getFormConfig();
  const pages  = config.admin.pages ?? [];
  const filtered = pages.filter((p) => p.autoGeneratedFor !== formId);
  if (filtered.length === pages.length) return 0;
  await saveFormConfig({ ...config, admin: { ...config.admin, pages: filtered } });
  return pages.length - filtered.length;
}

export interface BackfillResult {
  created: string[];
  skipped: string[];
}

/**
 * Idempotent: iterates over every form instance and creates an auto-page
 * for the ones that don't already have one bound to their id. Used by:
 *   - the boot pipeline when YAML enables the toggle
 *   - the restore endpoint when the incoming `admin.features` turns it on
 *   - the admin "Generate missing pages" button
 *
 * Skips silently when the toggle is off or the config isn't editable —
 * never auto-enables the feature on the caller's behalf.
 */
export async function backfillAutoViews(actor?: { id: string | null; email: string | null } | null): Promise<BackfillResult> {
  if (!isConfigEditable()) return { created: [], skipped: [] };
  const config = await getFormConfig();
  if (!config.admin.features?.autoCreateDashboardPageOnFormCreate) return { created: [], skipped: [] };

  const forms = await listFormInstances();
  const pages = [...(config.admin.pages ?? [])];
  const created: string[] = [];
  const skipped: string[] = [];

  for (const f of forms) {
    const exists = pages.some(
      (p) => p.formInstanceId === f.id || p.id === pageIdForForm(f.id),
    );
    if (exists) {
      skipped.push(f.slug);
      continue;
    }
    pages.push(buildAutoFormPage({ id: f.id, slug: f.slug, name: f.name }));
    created.push(f.slug);
  }

  if (created.length > 0) {
    await saveFormConfig({ ...config, admin: { ...config.admin, pages: pages } });
    logAdminEvent({
      userId:       actor?.id    ?? null,
      userEmail:    actor?.email ?? null,
      action:       "config.auto_pages.backfill",
      resourceType: "admin_config",
      resourceId:   "pages",
      details:      { created, skippedCount: skipped.length },
    });
  }
  return { created, skipped };
}
