/**
 * Centralised cleanup of every place a form id / slug is referenced outside
 * of the FK graph. Called from DELETE /api/admin/forms/[id] AFTER the form
 * row is dropped so cascading FKs have already cleared:
 *
 *   - submissions, submission_events, webhook_deliveries (CASCADE)
 *   - user_form_grants, form_version_history (CASCADE)
 *   - data_pool_sources, data_pool_submission_exclusions (CASCADE)
 *
 * The leftover references live in jsonb columns (no FK) and would otherwise
 * become zombie UUIDs that the UI silently skips:
 *
 *   - users.sidebar_layout  → pinnedForms[], formOrder[], favorites[],
 *                             categories[].formIds[]
 *   - saved_filters         → form_slug column (matching slug)
 *   - form_config.admin.views[] → manual views with formInstanceId === id;
 *                                 we unbind (set to undefined) so the view
 *                                 stays but turns into "all submissions",
 *                                 letting the operator re-bind it instead
 *                                 of losing widget config.
 *
 * Auto-generated views (`autoGeneratedFor === id`) are already deleted by
 * `removeAutoViewForForm` — we don't touch them here.
 */
import { db } from "@/lib/db";
import { users, savedFilters } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { getFormConfig, saveFormConfig, isConfigEditable } from "@/lib/config";
import type { SidebarLayout } from "@/types/sidebarLayout";

export interface PurgeResult {
  sidebarLayoutsUpdated: number;
  savedFiltersDeleted:   number;
  manualViewsUnbound:    number;
}

export async function purgeFormReferences(
  formId: string,
  formSlug: string,
): Promise<PurgeResult> {
  // ── 1. Strip the form id from every user's sidebar_layout ────────────
  const rows = await db
    .select({ id: users.id, sidebarLayout: users.sidebarLayout })
    .from(users);

  let sidebarLayoutsUpdated = 0;
  for (const row of rows) {
    const layout = row.sidebarLayout as SidebarLayout | null;
    if (!layout) continue;
    const cleaned = scrubLayoutForFormId(layout, formId);
    if (!cleaned) continue;
    await db.update(users).set({ sidebarLayout: cleaned }).where(eq(users.id, row.id));
    sidebarLayoutsUpdated++;
  }

  // ── 2. Drop saved filters tied to this form's slug ───────────────────
  // saved_filters.form_slug is a free-text column without FK — purge by slug
  // so historical filters don't accumulate references to a deleted form.
  const sfRes = await db
    .delete(savedFilters)
    .where(eq(savedFilters.formSlug, formSlug))
    .returning({ id: savedFilters.id });
  const savedFiltersDeleted = sfRes.length;

  // ── 3. Unbind manual admin.views whose formInstanceId === deleted ────
  // Auto-generated views are dropped elsewhere; we keep the manual ones but
  // null out the broken FK-in-JSON so widgets don't filter against a ghost.
  let manualViewsUnbound = 0;
  if (isConfigEditable()) {
    const config = await getFormConfig();
    const views = config.admin.views ?? [];
    let mutated = false;
    const next = views.map((v) => {
      if (v.formInstanceId === formId && !v.autoGeneratedFor) {
        mutated = true;
        manualViewsUnbound++;
        const { formInstanceId: _drop, ...rest } = v;
        return rest;
      }
      return v;
    });
    if (mutated) {
      await saveFormConfig({ ...config, admin: { ...config.admin, views: next } });
    }
  }

  return { sidebarLayoutsUpdated, savedFiltersDeleted, manualViewsUnbound };
}

/**
 * Returns a cleaned SidebarLayout if any reference to `formId` was removed,
 * or `null` when the layout doesn't mention the form (no DB write needed).
 */
function scrubLayoutForFormId(layout: SidebarLayout, formId: string): SidebarLayout | null {
  const has = (arr?: string[]) => Array.isArray(arr) && arr.includes(formId);
  let touched = false;

  const filterOut = (arr?: string[]): string[] | undefined => {
    if (!Array.isArray(arr)) return arr;
    if (!arr.includes(formId)) return arr;
    touched = true;
    return arr.filter((x) => x !== formId);
  };

  const nextLayout: SidebarLayout = { ...layout };
  if (has(layout.pinnedForms))         nextLayout.pinnedForms = filterOut(layout.pinnedForms);
  if (has(layout.formOrder))           nextLayout.formOrder   = filterOut(layout.formOrder);
  if (has(layout.favorites))           nextLayout.favorites   = filterOut(layout.favorites);

  if (Array.isArray(layout.categories)) {
    let categoriesTouched = false;
    const nextCategories = layout.categories.map((cat) => {
      if (!has(cat.formIds)) return cat;
      categoriesTouched = true;
      const nextFormIds = filterOut(cat.formIds) ?? [];
      // Also strip the formId from itemOrder if it appears as form:<id>
      const itemKey = `form:${formId}`;
      const nextItemOrder = Array.isArray(cat.itemOrder)
        ? cat.itemOrder.filter((k) => k !== itemKey)
        : cat.itemOrder;
      return { ...cat, formIds: nextFormIds, itemOrder: nextItemOrder };
    });
    if (categoriesTouched) {
      nextLayout.categories = nextCategories;
      touched = true;
    }
  }

  return touched ? nextLayout : null;
}
